  name: labfolder2elab
  channels:
    - https://repo.anaconda.com/pkgs/main
    - https://repo.anaconda.com/pkgs/r
  dependencies:
    - black
    - isort
    - mypy
    - notebook
    - numpy
    - pandas
    - pyarrow==19.0.0
    - pytest==8.4.1
    - python=3.12
    - ruff
    - types-requests
    - werkzeug==3.1.3
    - xlsxwriter
    - pip:
      - click==8.1.8
      - colorama==0.4.6
      - dynaconf==3.2.11
      - elapi==2.3.3
      - h11==0.14.0
      - h2==4.2.0
      - hpack==4.1.0
      - httpcore==0.17.3
      - httpx==0.24.1
      - httpx-auth==0.17.0
      - hyperframe==6.1.0
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - pip==25.2
      - rich==13.9.4
      - shellingham==1.5.4
      - typer==0.9.4
